services:
  beacon:
    build: .
    image: anoopvt/beacon_utils:latest
    ports:
      - "8765:8765"
    volumes:
      - beacon_data:/app
    restart: unless-stopped

volumes:
  beacon_data:
    name: beacon_data
